repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix, --ignore=E501]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pipreqs
        name: pipreqs
        description: Generate a requirements.txt file based on imports
        entry: bash -c 'pipreqs --force .'
        language: system
        pass_filenames: false
        types: [python]
