fetch_data_task:
  description: >
    使用yfinance获取{stock_ticker}的最新股票数据。
    使用TA库计算移动平均线收敛散度（MACD）指标。
    专注于最新的数据点以确保分析的及时性。
    预期输出：包含最新时间戳、收盘价、MACD值和MACD信号线值的数据结构（例如，字典或pandas系列）。
  goal: 获取{stock_ticker}的最新MACD数据。
  expected_output: 包含最新时间戳、收盘价、MACD值和MACD信号线值。

analyze_macd_task:
  description: >
    分析提供的{stock_ticker}的MACD数据。
    确定是否刚刚发生了看涨交叉（MACD线上穿信号线）或看跌交叉（MACD线下穿信号线）。
    根据交叉检测结果，决定交易行动：看涨时买入，看跌时卖出，否则持有。
    将决定（买入、卖出或持有）和相关的MACD数据传递到下一步。
    预期输出：表示交易决定的字符串（'BUY'、'SELL'或'HOLD'）。
  goal: 分析{stock_ticker}的MACD数据，并根据预定义的MACD交叉规则决定是否生成买入或卖出信号。
  expected_output: 表示交易决定的字符串（'BUY'、'SELL'或'HOLD'），以及做出该决定的原因。
  context:
    - fetch_data_task # 依赖于数据获取任务的输出

# execute_trade_task:
#   description: >
#     从交易策略师接收{stock_ticker}的交易决策。
#     如果决策是买入（BUY），使用'execute_buy_order'工具执行{quantity}股的市场买单。
#     如果决策是卖出（SELL），使用'execute_sell_order'工具执行{quantity}股的市场卖单。
#     如果决策是持有（HOLD），不采取任何行动。
#     记录所采取的行动（或没有采取行动）。
#     预期输出：确认订单是否已下达的消息（例如，"已成功下达10股AAPL的买单"，"已下达10股AAPL的卖单"，"决定持有，未执行交易"）。
#   context:
#     - analyze_macd_task # 依赖于分析任务的输出

generate_advice_task:
  description: >
    接收关于{stock_ticker}的股价信息和MACD分析结果（BUY、SELL或HOLD信号）。
    标题为：{stock_ticker} [买入/卖出/持有], 例如："AAPL [买入]"。
    内容为：
      1. 当前时间、股价、MACD值
      2. 当前的市场信号解释（为什么是买入/卖出/持有）
      3. 具体的操作建议（例如："建议以当前价格买入{quantity}股"）
      4. 可能的风险提示
      5. 后续关注点
    使用微信通知工具将这些建议发送给用户。
  goal: 生成详细的投资建议，并使用微信通知工具发送给用户。
  context:
    - fetch_data_task  # 依赖于数据获取任务的输出
    - analyze_macd_task  # 依赖于MACD分析任务的输出
  expected_output: "微信通知已发送，包含针对{stock_ticker}的投资建议。"