name: Hourly Script Execution

on:
  schedule:
    - cron: "0 * * * 1-5"
  push:
    branches:
      - master
      - dev
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple/
          if [ -f requirements.txt ]; then pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/; fi

      - name: Run script
        run: python main.py
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          TARGET_STOCK: ${{ secrets.TARGET_STOCK }}
          TRADE_QUANTITY: ${{ secrets.TRADE_QUANTITY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
