name: Hourly Script Execution (Backup)

on:
#   schedule:
#     - cron: "0 0,13 * * 1-5" # 每天0点、13点执行

  workflow_dispatch: # 手动触发
  push:
    branches:
      - master
      # - dev

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.11"

      - name: Debug Python paths
        run: |
          echo "Python executable: $(which python)"
          echo "Python version: $(python --version)"
          echo "Python site-packages:"
          python -c "import site; print(site.getsitepackages())"
          echo "User site-packages:"
          python -c "import site; print(site.getusersitepackages())"
          echo "Pip cache dir:"
          pip cache dir

      - name: Cache pip dependencies (simplified)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-cache-

      - name: Cache Python packages (simplified)
        uses: actions/cache@v4
        with:
          path: |
            /opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages
            /home/runner/.local/lib/python3.11/site-packages
          key: python-packages-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            python-packages-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple/
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --cache-dir ~/.cache/pip
          fi

      - name: Run script
        run: python main.py
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          TARGET_STOCK: ${{ secrets.TARGET_STOCK }}
          TRADE_QUANTITY: ${{ secrets.TRADE_QUANTITY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          LONGBRIDGE_APP_KEY: ${{ secrets.LONGBRIDGE_APP_KEY }}
          LONGBRIDGE_APP_SECRET: ${{ secrets.LONGBRIDGE_APP_SECRET }}
          LONGBRIDGE_ACCESS_TOKEN: ${{ secrets.LONGBRIDGE_ACCESS_TOKEN }} 